##### Ad-hoc conda apptainer #####

container: "docker://mambaorg/micromamba"

##### Import config #####

configfile: "config/config_file.yaml"

##### Load rules #####

include: "rules/common.smk"
include: "rules/cutadapt.smk"
include: "rules/pandaseq.smk"
include: "rules/vsearch.smk"
include: "rules/stats.smk"
include: "rules/generate_mutants.smk"
include: "rules/parse_fasta.smk"
include: "rules/process_read_counts.smk"

##### Target(s) #####
rule all:
    input:
        get_target()